config/routes.rb
Rails.application.routes.draw do
    root 'recipes#index'
    resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  def light?
    if calories!=nil
         calories < 100

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes= Recipe.all

    end
    def show
      @recipe= Recipe.find(params[:id])

    end
    def edit
      @recipe= Recipe.find(params[:id])

    end
    def update
      @recipe=Recipe.find(params[:id])
      recipe_params= params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost)
      @recipe.update(recipe_params)
      redirect_to @recipe

    end
    def new
        @recipe=Recipe.new

    end
    def create
        recipe_params = params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost)
        @recipe=Recipe.create(recipe_params)
        redirect_to recipes_url

    end
    def destroy
        @recipe=Recipe.find(params[:id])
        @recipe.destroy
        redirect_to recipes_url

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

 def format_calories(recipe)
        if recipe.light?
          content_tag(:strong, 'Light (contem menos de 100 calorias)')
        else
          recipe.calories
        end
 end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receitasnet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<%= form_for(@recipe) do |f| %>
   <h1>Editar Receitas</h1>
   <h4><%= @recipe.name.upcase %></h4>
    <p>
      <%= f.label :Nome %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :Ingredientes %><br />
      <%= f.text_area :stuff, cols:40, rows: 5 %>
   </p>
   <p>
      <%=f.label :Calorias %><br />
      <%= f.number_field :calories %>
   </p>
   <p>
      <%= f.label :Modo_de_preparo %><br />
      <%= f.text_area :prepare_mode, cols:50, rows: 5 %>
   </p>
   <p>
      <%= f.label :Custo %><br />
      <%= f.number_field :cost %>
   </p>
   <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<h1>Receitas</h1>
<table id="example" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>nome:</th>
            <th>Ingredientes:</th>
            <th>calorias:</th>
            <th>modo de preparo:</th>
            <th>Custo de preparo:</th>
        </tr>
    </thead>
    <tbody>
        <%@recipes.each do |recipe|%>
            <tr>
                <th><%= link_to recipe.name ,   recipe %></th>
                <th><%= truncate(recipe.stuff, lenght: 50, separator: ' ' ) %></th>
                <th>
                  <%=format_calories(recipe)%>
                </th>
                <th><%= recipe.prepare_mode %></th>
                <th><%= number_to_currency(recipe.cost) %></th>
            </tr>
        <%end%>
        <%= link_to "Nova Receita", new_recipe_path %>
    </tbody>
</table>

app/views/recipes/new.html.erb
<%= form_for(@recipe) do |f| %>
   <h1>Nova Receita</h1>
    <p>
      <%= f.label :Nome %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :Ingredientes %><br />
      <%= f.text_area :stuff, cols:40, rows: 5 %>
   </p>
   <p>
      <%=f.label :Calorias %><br />
      <%= f.number_field :calories %>
   </p>
   <p>
      <%= f.label :Modo_de_preparo %><br />
      <%= f.text_area :prepare_mode, cols:50, rows: 5 %>
   </p>
   <p>
      <%= f.label :Custo %><br />
      <%= f.number_field :cost %>
   </p>
   <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<article>
  <body>
    <h1><%=@recipe.name%></h1>
    <div class="">
      <h2>Ingredientes:</h2>
      <p><%=@recipe.stuff%></p>
    </div>
    <div class="">
      <h2>Calorias:</h2>
      <p><%=@recipe.calories%></p>
    </div>
    <div class="">
      <h2>Modo de preparo:</h2>
      <p><%=@recipe.prepare_mode%></p>
    </div>
    <div class="">
      <h2>Custo de preparo:</h2>
      <p><%=number_to_currency(@recipe.cost)%></p>
    </div>
    <%= link_to "Voltar as Receitas", recipes_path %>
    <%= link_to "Editar Receita", edit_recipe_path %>
    <%= link_to "Deletar Receita", recipe_path, method: :DELETE, data:{confirm: "Deseja Realmente Deletar a Receita ? "} %>
  </body>
</article>